# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: KubernetesManifest@1
  displayName: Deploying on GKE K8s
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'svc-k8s-cluster'
    namespace: 'default'
    manifests: |
      wp/secret.yaml
      wp/mysql-pvc.yaml
      wp/mysql-deployment.yaml
      wp/wordpress-pvc.yaml
      wp/wordpress-deployment.yaml