---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-finalproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-finalproject
  template:
    metadata:
      labels:
        app: k8s-finalproject
    spec:
      containers:
      - name: k8s-finalproject
        image: mohdwazid/k8s-finalproject:27.01
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"