apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- wordpress-deployment.yaml

commonLabels:
  environment: DevSecOpsTraining


#images:
#- name: basilvarghese/myapp-frontend
#  newTag: latest

# namespace: dev

replicas:
- name: wordpress
  count: 5

namePrefix: stres-
#nameSuffix: -dev